### ISSUE TITLE
Custom Presets

### ISSUE THREAD

**Issue by TheNety** [SuperRonanCraft/BetterRTP#25]
**Plugin Version**: 2.10.1

**Request**: Hey, would it be possible to add something like a teleport presets?

**How/Why**: Like you have CustomWorlds: ... There would be for example CustomPresets: and you can name it whatever you want, not just world name, for example "default" "vip" "admin" etc. and set a custom permission, cooldown and teleport distance for every preset.

**Additional Context**: Possible look in config:
```
CustomPresets:  
  VIP:  
    MaxRadius: 1000
    MinRadius: 10
    CenterX: 0
    CenterZ: 0
    permission: betterrtp.preset.vip
    cooldown: 100
    cost: 60 (ingame money)
```
