### ISSUE TITLE
BetterRTP can sometimes teleport into the air

### ISSUE THREAD

**Issue by Mario359** [SuperRonanCraft/BetterRTP#33]
**Plugin Version**: 2.10.1

**Issue Type**:
With a lot of teleportation attempts on dimensions (Nether or Ender) it sometimes happens that BetterRTP places the player in the air making him fall on the ground, in the void or in the lava.

**Context**:
I use the commands /rtp world world_nether or /rtp player <player> world_nether to teleport my players
The map is generated entirely within the teleport distance of BetterRTP
I use Minecraft 1.15.2 with Paper 347
![image](https://user-images.githubusercontent.com/20285750/84541911-a9459d00-acf8-11ea-9317-97f4504c78cd.png)

**Configuration**:
```
Language-File: fr.yml
Settings:
  RespectWorldGuard: false
  RespectGriefPrevention: false
  RespectSavageFactions: false
  MinRadius: 25
  MaxAttempts: 15
  Cooldown:
    Enabled: true
    Time: 900
  Delay:
    CancelOnDamage: true
    Time: 1
    CancelOnMove: true
  DisableUpdater: false
Default:
  UseWorldBorder: false
  Biomes: []
  MaxRadius: 10000
  MinRadius: 512
  CenterX: 0
  CenterZ: 0
BlacklistedBlocks:
- stationary_water
- stationary_lava
- water
- lava
- cactus
- leaves
- leaves_2
- air
- bedrock
- void
- void_air
- fire
- chorus_plant
- chorus_flower
DisabledWorlds: []
CustomWorlds:
- world:
    UseWorldBorder: false
    MaxRadius: 10000
    MinRadius: 512
    CenterX: 0
    CenterZ: 0
- world_nether:
    MaxRadius: 10000
    MinRadius: 1000
    CenterX: 0
    CenterZ: 0
- world_the_end:
    MaxRadius: 10000
    MinRadius: 1256
    CenterX: 0
    CenterZ: 0
Override:
  world_nether: world_nether
```

Note: Sometimes BetterRTP teleports in a single block of height, it's not annoying in 1.15 but it can be in 1.8
