### ISSUE TITLE
Add a list of command that will run on teleport complete

### ISSUE THREAD

**Issue by alan67160** [SuperRonanCraft/BetterRTP#55]
**Plugin Version**:
Version 3.0.3

**Request**:
Add a list of command that will run on teleport complete

**How/Why**:
because if we have the list, then we will have more customization like after RTP give some item, take some item or **set spawnpoint**

**Additional Context**:
Also, I suggesting this is because SetAsRespawn features is can't be trust
if you create a bed spawn point and then break the bed then your spawn point will back to world spawn point
```yml
  RtpOnFirstJoin:
    Enabled: true
    World: world
    SetAsRespawn: true
```
