### ISSUE TITLE
Can't use command /betterrtp location ...

### ISSUE THREAD

**Issue by LowScarlet** [SuperRonanCraft/BetterRTP#82]
**Plugin Version**:
ersion #3.1.0-5

**Describe The Bug**:
Can't use that command

**How To Reproduce**:
location.yml
```yaml
Enabled: true
Locations:
  world_low:
    World: world
    CenterX: 0
    CenterZ: 0
    MaxRadius: 7500
    MinRadius: -7500
    Shape: square
```
/betterrtp location world_low:

**Expected Behavior**:
trigger random teleport radius -7500 - 7500 from center 0

**Screenshots/Error Log**:

**Additional Context**:
